name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      actions: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v2
    
      - uses: docker/build-push-action@v4
        with:
          context: .
          file: "Dockerfile"
          tags: ci
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          push: false
          target: ci

      - name: Run CI
        uses: addnab/docker-run-action@v3
        with:
          image: ci
          run: GITHUB_TOKEN="${{ secrets.GITHUB_TOKEN }}" make ci